language: python
python:
 - "3.9"
addons:
  apt:
    packages:
      - openjdk-8-jre

install:
 - pip install html5validator

script: html5validator index.html japanese.html japanese2.html about.html --root _site/

branches:
  only:
    - master
    - dev