language: python
python:
 - "2.7"
addons:
  apt:
    packages:
      - openjdk-8-jre  

install:
 - pip install html5validator

script: html5validator index.html --root _site/

branches:
  only:
    - master
    - dev