# Generated by Django 3.2.8 on 2021-10-23 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_comments_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
