name: Django CI

on:
  push:
    branches: 
    - master
    - dev
  pull_request:
    branches:
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Upgrade Pip + Install Pipenv
      run: |
        python -m pip install --upgrade pip pipenv
    - name: Install all Pipenv Dependencies
      run: |
        pipenv install
    - name: Run Django Tests
      working-directory: ./DeltalineDjango
      run: |
        pipenv run python manage.py test
