name: Docker CI/CD

on: 
  push:
    branches:
      - master
      - dev 
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/no767/deltaline:2.1.2
    - name: Run Docker Image
      run: | 
        docker run ghcr.io/no767/deltaline:2.1.2
    - name: Push Docker Image to GitHub Registry
      run: |
        docker push ghcr.io/no767/deltaline:2.1.2
    