name: Format (Python)
on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10.2
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Upgrade Pip and Install Pipenv
        run: |
          pip install --upgrade pip pipenv
      - name: Cache Pipenv
        id: cache-pipenv
        uses: actions/cache@v2.1.7
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-v2-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install Pipenv Dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev
          run: |
            pipenv run black Deltaline-Sanic/
      - name: Format with Isort
        run: |
          pipenv run isort Deltaline-Sanic/
      - name: Format with AutoPEP8
        run: |
          pipenv run autopep8 -r --in-place Deltaline-Sanic/
      - name: Format with AutoFlake
        run: |
          pipenv run autoflake --in-place --remove-unused-variables --remove-all-unused-imports --recursive Deltaline-Sanic/
      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Format Sanic App'
          add: 'Deltaine-Sanic/ --force --all'
          push: true
          branch: dev
          pull: '--no-rebase'
